version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  # backend:
  #   build: ./apps/backend
  #   container_name: backend
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mongo
  #     - redis
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/urlscanner
  #     - REDIS_HOST=redis

  # frontend:
  #   build: ./apps/frontend
  #   container_name: frontend
  #   ports:
  #     - '3001:3000'
  #   depends_on:
  #     - backend

volumes:
  mongo_data:
